export const ADDRESS_REGIST_TYPE = {
  SET_UPPER_ZIP_CODE: 'SET_UPPER_ZIP_CODE',
  SET_LOWER_ZIP_CODE: 'SET_LOWER_ZIP_CODE',
  SET_SELECTED_CITY: 'SET_SELECTED_CITY',
  SET_SELECTED_DISTRICT: 'SET_SELECTED_DISTRICT',
  SET_SELECTED_WARD: 'SET_SELECTED_WARD',
  SET_CITIES: 'SET_CITIES',
  SET_DISTRICTS: 'SET_DISTRICTS',
  SET_WARDS: 'SET_WARDS',
  SET_CITY_DISTRICT_WARD_COMBINATION: 'SET_CITY_DISTRICT_WARD_COMBINATION',
  RESET: 'RESET'
}